#!/usr/bin/env bash
#
# Script to monitor disk usage.
#
GMETRIC=$(which gmetric)
[[ $? == 0 ]] || exit 0

clean_name() {
  echo $1 $7 $2 | sed 's/[\/.-]/_/g'| awk "{ 
  if (\$3 == \"tmpfs\")
    n=\$1\$2
  else
    n=\$1
    print n
  }"
}

os=$(uname | tr '[:upper:]' '[:lower:]')

if [ "$os" == "linux" ]; then
  CMD=$(df -T -P -l -x none -x unknown -x udf -x iso9660 -x romfs -x ramfs -x proc -x sysfs -x tmpfs -x udev | sed 1d | grep -v \"//\")
elif [ "$os" == "darwin" ]; then
  CMD=$(df -k -T hfs,msdos,ufs,zfs,xfs,ntfs | sed 1d | grep -v \"//\")
elif [ "$os" == "freebsd" ]; then
  CMD=$(df -k -t ufs,zfs,xfs,msdosfs,ntfs | sed 1d | grep -v \"//\")
fi


GMETRIC="${GMETRIC} --type=uint16 --units=% --dmax=3600 --tmax=1800"
echo "$CMD" | while read i; do
  name=`clean_name $i`
  VAL=$(echo $i | awk '{ print $(NF-1) }' | cut -f1 -d%)
  ${GMETRIC} --name="DiskUsed Percent ${name}" --value=${VAL}
done
