#!/bin/bash

# $Id: lmstat 1299 2008-05-12 14:55:08Z admin $

# author: udo waechter, 2007-07-21
#
# Macrovision license manager statistics - Get current licenses usage
GMETRIC=$(which gmetric)
[[ -x $GMETRIC ]] || exit 0
MATLAB=/opt/matlab
LMSTAT=${MATLAB}/etc/lmstat

[ -e ${LMSTAT} ] || exit 0;

TOOLBOXES=$($LMSTAT -a |grep issued |sed s/Users\ of\ //g |cut -f 1 -d: |tr  \\n \ )

G_NAME="License Use"
G_TYPE="uint8"
G_UNITS="Usage"

for TBOX in $TOOLBOXES; do
	VAL=$($LMSTAT -f $TBOX |grep "Users of" | cut -f 2 -d \; |sed s/[^[:digit:]]//g)
	$GMETRIC --dmax=30000 --tmax=300 --name="${G_NAME} ${TBOX}" --value=${VAL} --type=${G_TYPE} --units=${G_UNITS}
done
