#!/usr/bin/env bash
# $Id: lmstat 1299 2008-05-12 14:55:08Z admin $

# author: udo waechter, 2007-07-21
#
# Macrovision license manager statistics - Get current licenses usage
GMETRIC=$(which gmetric)
[[ -x $GMETRIC ]] || exit 0
MATLAB=/opt/matlab
LMSTAT=${MATLAB}/etc/lmstat

[ -e ${LMSTAT} ] || exit 0;

TOOLBOXES=$($LMSTAT -a |grep issued |sed s/Users\ of\ //g |cut -f 1 -d: |tr  \\n \ )

G_NAME="License Use"
G_TYPE="uint8"
G_UNITS="Usage"

GMETRIC="${GMETRIC} --slope=positive --dmax=30000 --tmax=300  --type=${G_TYPE} --units=${G_UNITS}"

for TBOX in $TOOLBOXES; do
    OUT=$($LMSTAT -f $TBOX)
    TOTAL=$(echo "$OUT"|grep "Users of" | cut -f 1 -d \; |sed s/[^[:digit:]]//g)
    $GMETRIC --name="${G_NAME} ${TBOX} total" --value=${TOTAL}
	VAL=$(echo "$OUT"|grep "Users of" | cut -f 2 -d \; |sed s/[^[:digit:]]//g)
	$GMETRIC --name="${G_NAME} ${TBOX}" --value=${VAL}
	LOCAL=$(echo "$OUT"| grep -e '\/dev' |grep  -e '[pts|ttys]' |wc -l)
	$GMETRIC --name="${G_NAME} ${TBOX} local" --value=${LOCAL}
	GRID=$(expr ${VAL} - ${LOCAL})
	$GMETRIC --name="${G_NAME} ${TBOX} grid" --value=${GRID}
done
