#!/usr/bin/env ruby

gmetric = %x{which gmetric}.chomp
exit 0 if $? != 0

readings = %x{ipmitool sdr list 2>/dev/null | grep -v "Not Readable" |grep -v "0x" |grep -v disabled | grep -v ns | grep -v nr}
#readings = File.open("sensread.txt").read
hsh = {}
idx=0
readings.each{ |line|
  l = line.chomp.split('|')
  l.each_index { |index|
    l[index].rstrip!
    l[index].lstrip!
  }
  label= l[0]
  if hsh.has_key? label
  label = "#{label}#{idx}"
  idx=idx.succ
  end
  hsh[label] = l[1,line.length-1]
}
hsh.each_key { |key|
  key2 = key.gsub(/\//,'_')
    #puts ">>#{hsh[key][0]}<<"
  value = hsh[key][0].gsub(/^([0-9\.-]+)\s.*/, '\1').to_f.abs
  units = hsh[key][0].gsub(/^([0-9\.-]+)\s+(.*)/, '\2')
  #puts "#{gmetric} --dmax=3600 --name=\"Sensors #{key2}\" --value=#{value} --units=\"#{units}\" --type=float --tmax=300"
  %x{#{gmetric} --dmax=3600 --name="Sensors #{key2}" --value=#{value} --units="#{units}" --type=float --tmax=300 }
}
