#!/usr/bin/ruby

readings = %x{ipmitool sensor 2>/dev/null}
#readings = File.open("sensread.txt").read
hsh = {}
idx=0
readings.each{ |line|
  l = line.chomp.split('|')
  l.each_index { |index|
    l[index].rstrip!
    l[index].lstrip!
  }
  label= l[0]
  if hsh.has_key? label
  label = "#{label}#{idx}"
  idx=idx.succ
  end
  hsh[label] = l[1,line.length-1]
}
result={}
hsh.each_key { |key|
  unless  hsh[key][0].eql?("na") or hsh[key][2].eql?("nr") or hsh[key][1].eql?("discrete") 
    result[key] = hsh[key]
  end
}
result.each_key { |key|
  key2 = key.gsub(/\//,'_')
  %x{gmetric --dmax=3600 --name="Sensors #{key2}" --value=#{result[key][0]} --units="#{result[key][1]}" --type=float --tmax=300}
}
