#!/usr/bin/env ruby 
# $Id: workusage 2202 2009-02-15 10:31:14Z uwaechte $
# created by udo.waechter@uni-osnabrueck.de, 2009-02-16
#
require 'etc'
# monitory diskusage on /work partition
work="/work"
#if the direcotry does not exist, do nothing
exit 0 unless File.exist?(work)

gmetric=%x{which gmetric}.chomp

statefile="/var/tmp/workusage.state"

#Create or update (every 10 hours) the file 
if (! File.exist?(statefile)) || (File.mtime(statefile).strftime("%H").to_i < (Time.new.strftime("%H").to_i - 10)) || File.size(statefile) == 0
  contents=Dir.glob("#{work}/??*")
  owners={}
  contents.each { |dir|
    if File.directory?(dir)
      uid=File.stat(dir).uid
      username=Etc.getpwuid(uid).name
      if !owners.key?(username)
	owners[username] = []  
      end
      owners[username].push(dir)
    end
  }

  stats = File.new(statefile,"w")
  owners.keys.each { |username|
    size = 0
    owners[username].each { |dir|
      s = %x{du -s "#{dir}" |cut -f 1}.chomp
      size +=  s.to_f
    }
    %x{gmetric --dmax=30000 --tmax=3600 --units="Kilobytes" --name=workusage_#{username} --value=#{size} --type="float"}
  }
  stats.close
else
  File.new(statefile,"r").each { |line| 
    keyval = line.split(" ")  
    %x{gmetric --dmax=30000 --tmax=3600 --units="Kilobytes" --name=workusage_#{keyval[0]} --value=#{keyval[1]} --type="float"}
  }
end
